import json


def detect_compilation_error(json_report):
    """
    Detects if there were any compilation errors based on the pytest JSON report.

    Parameters:
    - json_report (str): The JSON string generated by pytest with the --json-report option.

    Returns:
    - bool: True if a compilation error was detected, False otherwise.
    - str: A message indicating the result.
    """
    try:
        # Load the JSON report
        # report = json.loads(json_report)
        report = json_report

        # Check the exit code: 1 indicates an error, 3 means no tests were run, 0 is success
        if report['exitcode'] == 1:
            return True, "Compilation or syntax errors detected during test collection."

        # If exit code is 3, no tests were executed, check if it was because of no test collection
        if report['exitcode'] == 3 and report['summary']['collected'] == 0:
            return True, "No tests were collected, possibly due to compilation errors."

        # If exit code is 0 and tests were collected, no compilation errors occurred
        if report['exitcode'] == 0 or (report['exitcode'] == 3 and report['summary']['collected'] > 0):
            return False, "No compilation errors. Tests were collected successfully."

        # If none of the above, return a general message
        return False, "No compilation errors detected."

    except json.JSONDecodeError:
        return True, "Error parsing JSON report."
    except KeyError as e:
        return True, f"Missing expected key in JSON report: {e}"


if __name__ == "__main__":
    json_output = """{"created": 1724720379.079616, "duration": 0.01561427116394043, "exitcode": 3, "root": "/testbed", "environment": {}, "summary": {"total": 0, "collected": 7}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "testing/new_tests.py", "type": "Module"}]}, {"nodeid": "testing/new_tests.py", "outcome": "passed", "result": [{"nodeid": "testing/new_tests.py::test_collectonly_shortcut", "type": "Function", "lineno": 3}, {"nodeid": "testing/new_tests.py::test_collectonly_shortcut_with_other_options", "type": "Function", "lineno": 13}, {"nodeid": "testing/new_tests.py::test_collectonly_shortcut_no_tests", "type": "Function", "lineno": 23}, {"nodeid": "testing/new_tests.py::test_collectonly_shortcut_with_errors", "type": "Function", "lineno": 33}, {"nodeid": "testing/new_tests.py::test_collectonly_shortcut_with_ignore", "type": "Function", "lineno": 43}, {"nodeid": "testing/new_tests.py::test_collectonly_shortcut_with_ignore_glob", "type": "Function", "lineno": 60}, {"nodeid": "testing/new_tests.py::test_collectonly_shortcut_with_deselect", "type": "Function", "lineno": 77}]}], "tests": []}"""
    error_detected, message = detect_compilation_error(json_output)
    print(message)
